//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace WhatsAppApi.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("WhatsAppApi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Afghanistan&quot;,93,412,&quot;AF&quot;,&quot;ps&quot;
        ///&quot;Albania&quot;,355,276,&quot;AL&quot;,&quot;sq&quot;
        ///&quot;Alberta&quot;,1403,302,&quot;CA&quot;,&quot;en&quot;
        ///&quot;Alberta&quot;,1780,302,&quot;CA&quot;,&quot;en&quot;
        ///&quot;Algeria&quot;,213,603,&quot;DZ&quot;,&quot;ar&quot;
        ///&quot;Andorra&quot;,376,213,&quot;AD&quot;,&quot;ca&quot;
        ///&quot;Angola&quot;,244,631,&quot;AO&quot;,&quot;pt&quot;
        ///&quot;Anguilla&quot;,1264,&quot;365&quot;,&quot;AI&quot;,&quot;en&quot;
        ///&quot;Antarctica (Australian bases)&quot;,6721,232,&quot;AQ&quot;,&quot;en&quot;
        ///&quot;Antigua and Barbuda&quot;,1268,&quot;344&quot;,&quot;AG&quot;,&quot;en&quot;
        ///&quot;Argentina&quot;,54,722,&quot;AR&quot;,&quot;es&quot;
        ///&quot;Armenia&quot;,374,283,&quot;AM&quot;,&quot;hy&quot;
        ///&quot;Aruba&quot;,297,363,&quot;AW&quot;,&quot;nl&quot;
        ///&quot;Ascension&quot;,247,658,&quot;AC&quot;,&quot;en&quot;
        ///&quot;Australia&quot;,61,505,&quot;AU&quot;,&quot;en&quot;
        ///&quot;Austria&quot;,43,232,&quot;AT&quot;,&quot;de&quot;
        ///&quot; [re....
        /// </summary>
        internal static string countries {
            get {
                return ResourceManager.GetString("countries", resourceCulture);
            }
        }
    }
}
